name: Container Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  container-release:
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    uses: berntpopp/genefoundry-router/.github/workflows/_container-release.yml@0122f6e6d8f6a9057b80134d7cacbf61c5bd2e84 # genefoundry-router v0.9.3
